import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    "header.brandSubtitlePublic": "Precision Terminal",
    "header.brandSubtitleApp": "Premium Wealth",
    "header.home": "Home",
    "header.features": "Features",
    "header.intelligence": "Intelligence",
    "header.signIn": "Sign in",
    "header.openTerminal": "Open terminal",
    "header.dashboard": "Panel",
    "header.transactions": "Transactions",
    "header.goals": "Goals",
    "header.settings": "Settings",
    "header.support": "Support",
    "header.logout": "Logout",
    "header.portfolioHealth": "Portfolio Health",
    "header.excellentStatus": "Excellent Status",
    "header.baseCurrency": "Base currency",
    "header.overview": "Overview",
    "header.newTransaction": "New transaction",
    "header.goToDashboard": "Go to dashboard",
    "header.goToMovements": "Go to movements",
    "header.goodMorning": "Good morning",
    "footer.title": "Start building your legacy today.",
    "footer.description":
      "Turn everyday transactions into a clear financial command center with analytics, multi-currency control, goals and a premium operating experience.",
    "footer.startGoogle": "Start with Google",
    "footer.explore": "Explore the system",
    "home.kicker": "Future of Wealth Management",
    "home.titleBefore": "Take command of your",
    "home.titleAccent": "financial destiny",
    "home.description":
      "Precision analytics, multi-currency control, financial goals and a calmer way to understand your money. Adia Finance turns everyday movements into a premium command center.",
    "home.getStarted": "Get started with Google",
    "home.openTerminal": "Open terminal",
    "home.explore": "Explore the system",
    "home.proofRealtime": "Live dashboard",
    "home.proofCurrencies": "Multi-currency ready",
    "home.proofGoals": "Goals and control",
    "home.sectionTitle": "Engineered for financial clarity",
    "home.sectionDescription":
      "The app already works as a real personal finance workspace. This redesign keeps that logic and elevates the way it feels.",
    "home.featureInsightTitle": "Executive insights",
    "home.featureInsightDesc":
      "Read your monthly variation, dominant category, savings score and goal progress as one clear financial narrative.",
    "home.featureCurrencyTitle": "Multi-currency command",
    "home.featureCurrencyDesc":
      "Work with a base currency, exchange rates and mixed transactions without losing visibility of your real balance.",
    "home.featureGoalTitle": "Goal precision",
    "home.featureGoalDesc":
      "Set monthly savings targets and expense limits with visual progress that tells you how close you are.",
    "home.featureWorkflowTitle": "Real operational workflow",
    "home.featureWorkflowDesc":
      "Transactions, filters, import/export Excel, categories, settings and Firebase persistence are already part of the product.",
    "home.goToDashboard": "Go to dashboard",
    "home.signInNow": "Sign in now",
    "home.statViews": "Core views",
    "home.statMetrics": "Financial metrics",
    "home.statExcel": "Import and export",
    "home.statCloud": "Cloud persistence",
    "login.secureGoogle": "Secure Google access",
    "login.titleBefore": "Welcome",
    "login.titleAccent": "back",
    "login.subtitle":
      "Access your financial workspace with the authentication flow already connected in Firebase.",
    "login.brandSubtitle": "Premium Wealth Management Terminal",
    "login.google": "Sign in with Google",
    "login.loading": "Signing in...",
    "login.copyBefore":
      "The current product uses",
    "login.copyAccent": "Google authentication",
    "login.copyAfter":
      "as the real login method. The premium layout is aligned to the design reference without adding flows that do not exist in the app.",
    "login.firebase": "Firebase auth",
    "login.cloud": "Cloud synced",
    "login.dark": "Dark terminal ready",
    "dashboard.loadingKicker": "Loading workspace",
    "dashboard.loadingTitle": "Syncing your financial data...",
    "dashboard.loadingDescription":
      "We are preparing your metrics, transactions and settings from Firebase.",
    "dashboard.welcomeBack": "Welcome back, {name}",
    "dashboard.fallbackName": "Architect",
    "dashboard.titleBefore": "Your wealth is",
    "dashboard.titleAccent": "accelerating.",
    "dashboard.description":
      "Monitor income, expenses, savings goals, categories and recent movements from a single premium financial command center for {period}.",
    "dashboard.latestCycle": "the latest cycle",
    "dashboard.periodLabel": "Period",
    "dashboard.periodWeek": "Week",
    "dashboard.periodMonth": "Month",
    "dashboard.periodYear": "Year",
    "dashboard.periodCustom": "Custom",
    "dashboard.periodFrom": "From",
    "dashboard.periodTo": "To",
    "dashboard.selectedRange": "Selected range: {period}",
    "dashboard.totalBalance": "Total balance",
    "dashboard.vsPreviousMonth": "vs previous month",
    "dashboard.monthlyIncome": "Period income",
    "dashboard.monthlyExpense": "Period expense",
    "dashboard.savingsScore": "Savings score",
    "dashboard.scoreFootnote":
      "Score based on savings, consistency and expense ratio",
    "dashboard.incomeVsExpenses": "Income vs. expenses",
    "dashboard.periodSummary": "Performance for {period} in {currency}.",
    "dashboard.income": "Income",
    "dashboard.expenses": "Expenses",
    "dashboard.showingRecords": "Showing {count} matching records.",
    "dashboard.exportExcel": "Export Excel",
    "dashboard.downloadTemplate": "Download template",
    "dashboard.importExcel": "Import Excel",
    "dashboard.importSuccess": "{count} transactions imported correctly",
    "dashboard.extendedAnalytics": "Extended analytics",
    "dashboard.extendedAnalyticsDesc":
      "Support metrics preserved from the original project and styled into the new visual system.",
    "dashboard.quickActions": "Quick actions",
    "dashboard.quickActionsDesc":
      "Keep your financial loop moving without leaving the dashboard.",
    "dashboard.goToMovements": "Go to movements",
    "dashboard.manageMovements": "Manage movements",
    "dashboard.upgradeTitle": "Upgrade your routine",
    "dashboard.upgradeDesc":
      "Use import/export, categories and financial goals together to turn the dashboard into a real monthly operating system.",
    "dashboard.addNow": "Add transaction now",
    "dashboard.newTransaction": "New transaction",
    "dashboard.deleteToast": "Transaction deleted",
    "dashboard.savedToast": "Transaction saved correctly",
    "dashboard.updatedToast": "Transaction updated",
    "dashboard.aiKicker": "Adia AI Insight",
    "dashboard.aiTitle": "High precision signal",
    "dashboard.aiStable":
      "Your financial momentum is stable and under control.",
    "dashboard.aiImproved":
      "Your balance improved {value}% versus the previous month.",
    "dashboard.aiDropped":
      "Your balance dropped {value}% versus the previous month.",
    "dashboard.aiTopCategory": "Top spending category: {category}.",
    "dashboard.aiGoalReached": "Savings goal reached. Excellent discipline.",
    "dashboard.aiStrongScore":
      "Your financial score remains in a strong range.",
    "dashboard.bestMonth": "Best month",
    "dashboard.noData": "No data",
    "dashboard.addMoreHistory": "Add more movement history",
    "dashboard.highestExpenseMonth": "Highest expense month",
    "dashboard.noHistoricalExpense": "No historical expense yet",
    "dashboard.averageMonthlyFlow": "Average monthly flow",
    "dashboard.expensesAvg": "Expenses avg {value}",
    "dashboard.financialRatios": "Financial ratios",
    "dashboard.savedRatio": "{value}% saved",
    "dashboard.expenseRatio": "{value}% expense ratio",
    "filters.show": "Show filters",
    "filters.hide": "Hide filters",
    "filters.allTypes": "All types",
    "filters.searchCategory": "Search category",
    "filters.from": "From",
    "filters.to": "To",
    "filters.newest": "Newest first",
    "filters.oldest": "Oldest first",
    "filters.reset": "Reset",
    "transactions.noResultsTitle": "No results",
    "transactions.noResultsDesc":
      "No transactions match the current filters. Try widening the date range or clearing one filter.",
    "transactions.adjustFilters": "Adjust the active filters",
    "transactions.transaction": "Transaction",
    "transactions.category": "Category",
    "transactions.date": "Date",
    "transactions.currency": "Currency",
    "transactions.amount": "Amount",
    "transactions.actions": "Actions",
    "transactions.income": "Income",
    "transactions.expense": "Expense",
    "transactions.transactionFallback": "Transaction",
    "transactions.noDate": "No date",
    "transactions.edit": "Edit",
    "transactions.delete": "Delete",
    "transactions.confirmDelete": "Delete this transaction?",
    "transactionForm.new": "New transaction",
    "transactionForm.edit": "Edit transaction",
    "transactionForm.description":
      "Record a new financial movement using the premium modal layout from the prototype.",
    "transactionForm.enterAmount": "Enter amount",
    "transactionForm.income": "Income",
    "transactionForm.expense": "Expense",
    "transactionForm.category": "Category",
    "transactionForm.selectCategory": "Select category",
    "transactionForm.date": "Date",
    "transactionForm.descriptionLabel": "Description",
    "transactionForm.descriptionPlaceholder":
      "What happened in this transaction?",
    "transactionForm.cancel": "Cancel",
    "transactionForm.add": "Add transaction",
    "transactionForm.update": "Update transaction",
    "movements.kicker": "Transaction center",
    "movements.loadingTitle": "Loading your movements...",
    "movements.loadingDescription":
      "We are preparing your income and expense history from Firebase.",
    "movements.titleBefore": "Review and manage your",
    "movements.titleAccent": "movements.",
    "movements.description":
      "Use this view to register, filter, edit and delete income and expense transactions in one place.",
    "movements.listTitle": "All movements",
    "movements.dashboardCardTitle": "Your movements now have their own space",
    "movements.dashboardCardDescription":
      "Open the movements view to work with income and expenses in list format, with filters and direct editing.",
    "goals.manageKicker": "Goals center",
    "goals.manageTitleBefore": "Create and track your",
    "goals.manageTitleAccent": "goals.",
    "goals.manageDescription":
      "Define personalized savings goals and decide which one should be reflected on the dashboard.",
    "goals.createTitle": "New savings goal",
    "goals.createDescription":
      "You can create weekly, monthly, yearly, fixed-range or open-ended goals.",
    "goals.goalName": "Goal name",
    "goals.goalNamePlaceholder": "Example: Emergency fund",
    "goals.targetAmount": "Target amount",
    "goals.goalCurrency": "Goal currency",
    "goals.goalType": "Goal type",
    "goals.typeWeekly": "Weekly",
    "goals.typeMonthly": "Monthly",
    "goals.typeYearly": "Yearly",
    "goals.typeCustom": "Custom range",
    "goals.typeOpen": "Until target amount",
    "goals.startDate": "Start date",
    "goals.endDate": "End date",
    "goals.createAction": "Create goal",
    "goals.formError": "Complete the name and a valid target amount.",
    "goals.rangeError": "Choose both start and end dates for a custom goal.",
    "goals.dashboardTitle": "Dashboard reflection",
    "goals.dashboardDescription":
      "The active goal below is the one used by the dashboard progress card.",
    "goals.operationalTitle": "Spending control",
    "goals.operationalDescription":
      "Set the monthly spending limit that also appears on the dashboard.",
    "goals.operationalCurrency": "This limit will be saved in {currency}.",
    "goals.saveOperational": "Save spending limit",
    "goals.activeGoal": "Active goal",
    "goals.noneActive": "No active goal",
    "goals.currentSaved": "Current saved amount",
    "goals.listTitle": "Saved goals",
    "goals.listDescription":
      "Activate one goal at a time to show it on the dashboard.",
    "goals.visibleOnDashboard": "Visible on dashboard",
    "goals.available": "Available",
    "goals.currentDashboardGoal": "Current dashboard goal",
    "goals.useOnDashboard": "Use on dashboard",
    "goals.deleteGoal": "Delete goal",
    "goals.emptyTitle": "No goals yet",
    "goals.emptyDescription":
      "Create your first personalized savings goal to start tracking it from the dashboard.",
    "goals.typeLabel.weekly": "Weekly",
    "goals.typeLabel.monthly": "Monthly",
    "goals.typeLabel.yearly": "Yearly",
    "goals.typeLabel.custom_range": "Custom range",
    "goals.typeLabel.open_ended": "Until target amount",
    "goals.title": "Financial Goals",
    "goals.description":
      "Savings progress and monthly expense control in one place.",
    "goals.savings": "Savings",
    "goals.needMore":
      "You still need {value} to reach your target.",
    "goals.defineTarget":
      "Define a savings target from settings to activate this block.",
    "goals.monthlySavings": "Monthly savings target",
    "goals.monthlySpending": "Monthly spending limit",
    "categories.title": "Top Categories",
    "categories.description":
      "A quick breakdown of the categories driving your spend this period.",
    "categories.thisMonth": "This month",
    "categories.viewDetailed": "View detailed report",
    "settings.kicker": "System settings",
    "settings.titleBefore": "Configure your",
    "settings.titleAccent": "workspace.",
    "settings.subtitle":
      "The forms below are the real settings connected to your current app: currency base, exchange entries, categories and financial goals.",
    "settings.languageTitle": "Language",
    "settings.languageDesc":
      "Choose how the redesigned interface should be displayed.",
    "settings.languageEnglish": "English",
    "settings.languageSpanish": "Spanish",
    "settings.summaryTitle": "Workspace summary",
    "settings.summaryDesc": "Live counters derived from the current data model.",
    "settings.baseCurrency": "Base currency",
    "settings.activeCurrencies": "Active currencies",
    "settings.activeCategories": "Active categories",
    "settings.currentGoalSignals": "Current goal signals",
    "settings.currentGoalSignalsDesc":
      "These indicators reflect the values used by the dashboard cards.",
    "settings.goalsMovedTitle": "Goals moved to Goals",
    "settings.goalsMovedDesc":
      "Create and manage savings goals and spending limits from the dedicated Goals view.",
    "settings.goalsMovedAction": "Open Goals",
    "settings.savingsTarget": "Savings target",
    "settings.expenseLimit": "Expense limit",
    "settings.privacy": "Privacy policy",
    "settings.apiReady": "API ready data model",
    "settings.protocol": "Adia finance protocol 2026",
    "settings.baseCurrencyTitle": "Base currency",
    "settings.baseCurrencyDesc":
      "Choose the reference currency used by analytics and goals.",
    "settings.liveSetting": "Live setting",
    "settings.rateLabel": "Rate {value}",
    "settings.saveBaseCurrency": "Save base currency",
    "settings.baseSaved": "Base currency updated correctly.",
    "settings.baseError": "An error occurred updating the base currency.",
    "settings.baseMissing": "The selected currency does not exist.",
    "settings.baseDisabled": "The selected currency is disabled.",
    "settings.baseInvalidRate": "The selected currency has an invalid rate.",
    "settings.currencyManagement": "Currency management",
    "settings.currencyManagementDesc":
      "Keep your exchange rates updated and decide which currencies stay active in the app.",
    "settings.fixedDefaultCurrency": "Fixed default currency",
    "settings.currentBaseCurrency": "Current base currency",
    "settings.customExchangeEntry": "Custom exchange entry",
    "settings.active": "Active",
    "settings.remove": "Remove",
    "settings.addCurrency": "Add currency",
    "settings.currencyCodeError": "Code must have 3 letters (eg: EUR).",
    "settings.currencyRateError": "Rate must be greater than 0.",
    "settings.currencyExists": "The currency already exists.",
    "settings.categoryManagement": "Category management",
    "settings.categoryManagementDesc":
      "Keep income and expense categories organized with color coding and safe deactivation rules.",
    "settings.income": "Income",
    "settings.expense": "Expense",
    "settings.deactivate": "Deactivate",
    "settings.newCategoryName": "New category name",
    "settings.addCategory": "Add category",
    "settings.categoryNameRequired": "Name is required.",
    "settings.categoryExists": "The category already exists.",
    "settings.financialGoals": "Financial goals",
    "settings.financialGoalsDesc":
      "Define the savings target and monthly spending guardrail used by the dashboard.",
    "settings.monthlySavingsTarget": "Monthly savings target",
    "settings.monthlyExpenseLimit": "Monthly expense limit",
    "settings.monthly": "Monthly",
    "settings.quarterly": "Quarterly",
    "settings.yearly": "Yearly",
    "settings.saveGoals": "Save goals",
    "settings.saving": "Saving...",
    "settings.goalsSaved": "Goals saved correctly.",
    "settings.goalsError": "Error saving goals."
  },
  es: {
    "header.brandSubtitlePublic": "Terminal de Precision",
    "header.brandSubtitleApp": "Patrimonio Premium",
    "header.home": "Inicio",
    "header.features": "Funciones",
    "header.intelligence": "Inteligencia",
    "header.signIn": "Ingresar",
    "header.openTerminal": "Abrir terminal",
    "header.dashboard": "Dashboard",
    "header.transactions": "Movimientos",
    "header.goals": "Metas",
    "header.settings": "Configuración",
    "header.support": "Soporte",
    "header.logout": "Cerrar sesión",
    "header.portfolioHealth": "Salud financiera",
    "header.excellentStatus": "Estado excelente",
    "header.baseCurrency": "Moneda base",
    "header.overview": "Resumen",
    "header.newTransaction": "Nueva transacción",
    "header.goToDashboard": "Ir al dashboard",
    "header.goToMovements": "Ir a movimientos",
    "header.goodMorning": "Buen día",
    "footer.title": "Empieza a construir tu legado hoy.",
    "footer.description":
      "Convierte cada movimiento en un centro de mando financiero con anal\u00edtica, control multimoneda, metas y una experiencia premium.",
    "footer.startGoogle": "Empezar con Google",
    "footer.explore": "Explorar sistema",
    "home.kicker": "Nueva generaci\u00f3n de finanzas personales",
    "home.titleBefore": "Toma el control de tu",
    "home.titleAccent": "destino financiero",
    "home.description":
      "Anal\u00edtica precisa, control multimoneda, metas financieras y una forma m\u00e1s clara de entender tu dinero. Adia Finance convierte tus movimientos diarios en un centro de mando premium.",
    "home.getStarted": "Empezar con Google",
    "home.openTerminal": "Abrir terminal",
    "home.explore": "Explorar sistema",
    "home.proofRealtime": "Dashboard en vivo",
    "home.proofCurrencies": "Multimoneda real",
    "home.proofGoals": "Metas y control",
    "home.sectionTitle": "Pensado para la claridad financiera",
    "home.sectionDescription":
      "La app ya funciona como un espacio real de finanzas personales. Este redise\u00f1o conserva esa l\u00f3gica y eleva c\u00f3mo se siente usarla.",
    "home.featureInsightTitle": "Insights ejecutivos",
    "home.featureInsightDesc":
      "Lee variaci\u00f3n mensual, categor\u00eda dominante, score financiero y progreso de metas como una narrativa financiera clara.",
    "home.featureCurrencyTitle": "Control multimoneda",
    "home.featureCurrencyDesc":
      "Trabaja con moneda base, tasas de cambio y transacciones mixtas sin perder visibilidad del balance real.",
    "home.featureGoalTitle": "Precisi\u00f3n en metas",
    "home.featureGoalDesc":
      "Define objetivos de ahorro y l\u00edmites de gasto con un progreso visual que te muestra qu\u00e9 tan cerca est\u00e1s.",
    "home.featureWorkflowTitle": "Flujo operativo real",
    "home.featureWorkflowDesc":
      "Transacciones, filtros, importaci\u00f3n y exportaci\u00f3n Excel, categor\u00edas, configuraci\u00f3n y persistencia en Firebase ya forman parte del producto.",
    "home.goToDashboard": "Ir al dashboard",
    "home.signInNow": "Ingresar ahora",
    "home.statViews": "Vistas clave",
    "home.statMetrics": "M\u00e9tricas financieras",
    "home.statExcel": "Importar y exportar",
    "home.statCloud": "Persistencia cloud",
    "login.secureGoogle": "Acceso seguro con Google",
    "login.titleBefore": "Bienvenido",
    "login.titleAccent": "otra vez",
    "login.subtitle":
      "Accede a tu espacio financiero con el flujo de autenticaci\u00f3n que ya est\u00e1 conectado a Firebase.",
    "login.brandSubtitle": "Terminal premium de gesti\u00f3n patrimonial",
    "login.google": "Ingresar con Google",
    "login.loading": "Ingresando...",
    "login.copyBefore": "El producto actual usa",
    "login.copyAccent": "autenticaci\u00f3n con Google",
    "login.copyAfter":
      "como m\u00e9todo real de acceso. La capa premium respeta ese flujo sin inventar pantallas que no existen en la app.",
    "login.firebase": "Auth Firebase",
    "login.cloud": "Sincronizaci\u00f3n cloud",
    "login.dark": "Modo oscuro listo",
    "dashboard.loadingKicker": "Cargando espacio",
    "dashboard.loadingTitle": "Sincronizando tus datos financieros...",
    "dashboard.loadingDescription":
      "Estamos preparando m\u00e9tricas, transacciones y configuraciones desde Firebase.",
    "dashboard.welcomeBack": "Bienvenido otra vez, {name}",
    "dashboard.fallbackName": "Arquitecto",
    "dashboard.titleBefore": "Tu patrimonio esta",
    "dashboard.titleAccent": "acelerando.",
    "dashboard.description":
      "Monitorea ingresos, gastos, metas de ahorro, categor\u00edas y movimientos recientes desde un \u00fanico centro de mando premium para {period}.",
    "dashboard.latestCycle": "el \u00faltimo per\u00edodo",
    "dashboard.periodLabel": "Per\u00edodo",
    "dashboard.periodWeek": "Semana",
    "dashboard.periodMonth": "Mes",
    "dashboard.periodYear": "A\u00f1o",
    "dashboard.periodCustom": "Personalizado",
    "dashboard.periodFrom": "Desde",
    "dashboard.periodTo": "Hasta",
    "dashboard.selectedRange": "Rango seleccionado: {period}",
    "dashboard.totalBalance": "Balance total",
    "dashboard.vsPreviousMonth": "vs mes anterior",
    "dashboard.monthlyIncome": "Ingresos del per\u00edodo",
    "dashboard.monthlyExpense": "Gastos del per\u00edodo",
    "dashboard.savingsScore": "Score financiero",
    "dashboard.scoreFootnote":
      "Score basado en ahorro, consistencia y ratio de gasto",
    "dashboard.incomeVsExpenses": "Ingresos vs gastos",
    "dashboard.periodSummary": "Rendimiento para {period} en {currency}.",
    "dashboard.income": "Ingresos",
    "dashboard.expenses": "Gastos",
    "dashboard.showingRecords": "Mostrando {count} registros filtrados.",
    "dashboard.exportExcel": "Exportar Excel",
    "dashboard.downloadTemplate": "Descargar plantilla",
    "dashboard.importExcel": "Importar Excel",
    "dashboard.importSuccess": "{count} transacciones importadas correctamente",
    "dashboard.extendedAnalytics": "Anal\u00edtica extendida",
    "dashboard.extendedAnalyticsDesc":
      "M\u00e9tricas de apoyo preservadas del proyecto original y adaptadas al nuevo sistema visual.",
    "dashboard.quickActions": "Acciones r\u00e1pidas",
    "dashboard.quickActionsDesc":
      "Mantiene tu flujo financiero activo sin salir del dashboard.",
    "dashboard.goToMovements": "Ir a movimientos",
    "dashboard.manageMovements": "Gestionar movimientos",
    "dashboard.upgradeTitle": "Mejora tu rutina",
    "dashboard.upgradeDesc":
      "Usa importaci\u00f3n, exportaci\u00f3n, categor\u00edas y metas financieras juntas para convertir el dashboard en tu sistema mensual real.",
    "dashboard.addNow": "Agregar transacci\u00f3n ahora",
    "dashboard.newTransaction": "Nueva transacci\u00f3n",
    "dashboard.deleteToast": "Transacci\u00f3n eliminada",
    "dashboard.savedToast": "Transacci\u00f3n guardada correctamente",
    "dashboard.updatedToast": "Transacci\u00f3n actualizada",
    "dashboard.aiKicker": "Insight Adia AI",
    "dashboard.aiTitle": "Se\u00f1al de alta precisi\u00f3n",
    "dashboard.aiStable":
      "Tu impulso financiero se mantiene estable y bajo control.",
    "dashboard.aiImproved":
      "Tu balance mejor\u00f3 {value}% frente al mes anterior.",
    "dashboard.aiDropped":
      "Tu balance cay\u00f3 {value}% frente al mes anterior.",
    "dashboard.aiTopCategory": "Categor\u00eda dominante de gasto: {category}.",
    "dashboard.aiGoalReached": "Meta de ahorro alcanzada. Excelente disciplina.",
    "dashboard.aiStrongScore":
      "Tu score financiero se mantiene en una zona s\u00f3lida.",
    "dashboard.bestMonth": "Mejor mes",
    "dashboard.noData": "Sin datos",
    "dashboard.addMoreHistory": "Agrega m\u00e1s historial de movimientos",
    "dashboard.highestExpenseMonth": "Mes de mayor gasto",
    "dashboard.noHistoricalExpense": "Todav\u00eda no hay gasto hist\u00f3rico",
    "dashboard.averageMonthlyFlow": "Promedio mensual",
    "dashboard.expensesAvg": "Promedio de gasto {value}",
    "dashboard.financialRatios": "Ratios financieros",
    "dashboard.savedRatio": "{value}% ahorrado",
    "dashboard.expenseRatio": "{value}% ratio de gasto",
    "filters.show": "Mostrar filtros",
    "filters.hide": "Ocultar filtros",
    "filters.allTypes": "Todos los tipos",
    "filters.searchCategory": "Buscar categor\u00eda",
    "filters.from": "Desde",
    "filters.to": "Hasta",
    "filters.newest": "M\u00e1s recientes",
    "filters.oldest": "M\u00e1s antiguos",
    "filters.reset": "Resetear",
    "transactions.noResultsTitle": "Sin resultados",
    "transactions.noResultsDesc":
      "No hay transacciones que coincidan con los filtros actuales. Prueba ampliar la fecha o limpiar alg\u00fan filtro.",
    "transactions.adjustFilters": "Ajustar filtros activos",
    "transactions.transaction": "Transacci\u00f3n",
    "transactions.category": "Categor\u00eda",
    "transactions.date": "Fecha",
    "transactions.currency": "Moneda",
    "transactions.amount": "Monto",
    "transactions.actions": "Acciones",
    "transactions.income": "Ingreso",
    "transactions.expense": "Gasto",
    "transactions.transactionFallback": "Movimiento",
    "transactions.noDate": "Sin fecha",
    "transactions.edit": "Editar",
    "transactions.delete": "Eliminar",
    "transactions.confirmDelete": "\u00bfEliminar esta transacci\u00f3n?",
    "transactionForm.new": "Nueva transacci\u00f3n",
    "transactionForm.edit": "Editar transacci\u00f3n",
    "transactionForm.description":
      "Registra un nuevo movimiento financiero usando la composici\u00f3n premium de la app.",
    "transactionForm.enterAmount": "Ingresar monto",
    "transactionForm.income": "Ingreso",
    "transactionForm.expense": "Gasto",
    "transactionForm.category": "Categor\u00eda",
    "transactionForm.selectCategory": "Seleccionar categor\u00eda",
    "transactionForm.date": "Fecha",
    "transactionForm.descriptionLabel": "Descripci\u00f3n",
    "transactionForm.descriptionPlaceholder":
      "\u00bfQu\u00e9 pas\u00f3 en esta transacci\u00f3n?",
    "transactionForm.cancel": "Cancelar",
    "transactionForm.add": "Agregar transacci\u00f3n",
    "transactionForm.update": "Actualizar transacci\u00f3n",
    "movements.kicker": "Centro de movimientos",
    "movements.loadingTitle": "Cargando tus movimientos...",
    "movements.loadingDescription":
      "Estamos preparando tu historial de ingresos y gastos desde Firebase.",
    "movements.titleBefore": "Revisa y gestiona tus",
    "movements.titleAccent": "movimientos.",
    "movements.description":
      "Usa esta vista para registrar, filtrar, editar y eliminar transacciones de ingresos y egresos en un solo lugar.",
    "movements.listTitle": "Todos los movimientos",
    "movements.dashboardCardTitle": "Tus movimientos ya tienen su propio espacio",
    "movements.dashboardCardDescription":
      "Abre la vista de movimientos para trabajar ingresos y egresos en formato lista, con filtros y edici\u00f3n directa.",
    "goals.manageKicker": "Centro de metas",
    "goals.manageTitleBefore": "Crea y sigue tus",
    "goals.manageTitleAccent": "metas.",
    "goals.manageDescription":
      "Define metas de ahorro personalizadas y decide cu\u00e1l debe reflejarse en el dashboard.",
    "goals.createTitle": "Nueva meta de ahorro",
    "goals.createDescription":
      "Puedes crear metas semanales, mensuales, anuales, por rango fijo o abiertas hasta cumplir un monto.",
    "goals.goalName": "Nombre de la meta",
    "goals.goalNamePlaceholder": "Ejemplo: Fondo de emergencia",
    "goals.targetAmount": "Monto objetivo",
    "goals.goalCurrency": "Moneda de la meta",
    "goals.goalType": "Tipo de meta",
    "goals.typeWeekly": "Semanal",
    "goals.typeMonthly": "Mensual",
    "goals.typeYearly": "Anual",
    "goals.typeCustom": "Rango personalizado",
    "goals.typeOpen": "Hasta alcanzar el monto",
    "goals.startDate": "Fecha de inicio",
    "goals.endDate": "Fecha de cierre",
    "goals.createAction": "Crear meta",
    "goals.formError": "Completa el nombre y un monto objetivo v\u00e1lido.",
    "goals.rangeError": "Elige fecha de inicio y cierre para una meta personalizada.",
    "goals.dashboardTitle": "Reflejo en dashboard",
    "goals.dashboardDescription":
      "La meta activa de abajo es la que usa la tarjeta de progreso del dashboard.",
    "goals.operationalTitle": "Control de gasto",
    "goals.operationalDescription":
      "Define el l\u00edmite mensual de gasto que tambi\u00e9n aparece en el dashboard.",
    "goals.operationalCurrency": "Este l\u00edmite se guardar\u00e1 en {currency}.",
    "goals.saveOperational": "Guardar l\u00edmite de gasto",
    "goals.activeGoal": "Meta activa",
    "goals.noneActive": "Sin meta activa",
    "goals.currentSaved": "Ahorro acumulado actual",
    "goals.listTitle": "Metas guardadas",
    "goals.listDescription":
      "Activa una meta a la vez para mostrarla en el dashboard.",
    "goals.visibleOnDashboard": "Visible en dashboard",
    "goals.available": "Disponible",
    "goals.currentDashboardGoal": "Meta actual del dashboard",
    "goals.useOnDashboard": "Usar en dashboard",
    "goals.deleteGoal": "Eliminar meta",
    "goals.emptyTitle": "Todav\u00eda no tienes metas",
    "goals.emptyDescription":
      "Crea tu primera meta de ahorro personalizada para empezar a seguirla desde el dashboard.",
    "goals.typeLabel.weekly": "Semanal",
    "goals.typeLabel.monthly": "Mensual",
    "goals.typeLabel.yearly": "Anual",
    "goals.typeLabel.custom_range": "Rango personalizado",
    "goals.typeLabel.open_ended": "Hasta alcanzar el monto",
    "goals.title": "Metas financieras",
    "goals.description":
      "Progreso de ahorro y control del gasto mensual en un solo bloque.",
    "goals.savings": "Ahorro",
    "goals.needMore":
      "Todav\u00eda necesitas {value} para alcanzar tu meta.",
    "goals.defineTarget":
      "Define una meta de ahorro en configuraci\u00f3n para activar este bloque.",
    "goals.monthlySavings": "Meta mensual de ahorro",
    "goals.monthlySpending": "L\u00edmite mensual de gasto",
    "categories.title": "Categor\u00edas principales",
    "categories.description":
      "Un desglose r\u00e1pido de las categor\u00edas que m\u00e1s empujan tu gasto este per\u00edodo.",
    "categories.thisMonth": "Este mes",
    "categories.viewDetailed": "Ver reporte detallado",
    "settings.kicker": "Configuraci\u00f3n del sistema",
    "settings.titleBefore": "Configura tu",
    "settings.titleAccent": "espacio.",
    "settings.subtitle":
      "Los formularios de abajo son configuraciones reales conectadas a tu app actual: moneda base, tasas, categor\u00edas y metas financieras.",
    "settings.languageTitle": "Idioma",
    "settings.languageDesc":
      "La interfaz redise\u00f1ada queda establecida en espa\u00f1ol para todas las vistas principales.",
    "settings.languageEnglish": "Ingl\u00e9s",
    "settings.languageSpanish": "Espa\u00f1ol",
    "settings.summaryTitle": "Resumen del espacio",
    "settings.summaryDesc": "Contadores en vivo derivados del modelo de datos actual.",
    "settings.baseCurrency": "Moneda base",
    "settings.activeCurrencies": "Monedas activas",
    "settings.activeCategories": "Categor\u00edas activas",
    "settings.currentGoalSignals": "Se\u00f1ales actuales de metas",
    "settings.currentGoalSignalsDesc":
      "Estos indicadores reflejan los valores usados por las tarjetas del dashboard.",
    "settings.goalsMovedTitle": "Las metas ahora viven en Metas",
    "settings.goalsMovedDesc":
      "Crea y gestiona metas de ahorro y l\u00edmites de gasto desde la vista dedicada de Metas.",
    "settings.goalsMovedAction": "Abrir Metas",
    "settings.savingsTarget": "Meta de ahorro",
    "settings.expenseLimit": "L\u00edmite de gasto",
    "settings.privacy": "Pol\u00edtica de privacidad",
    "settings.apiReady": "Modelo de datos listo para API",
    "settings.protocol": "Protocolo Adia Finance 2026",
    "settings.baseCurrencyTitle": "Moneda base",
    "settings.baseCurrencyDesc":
      "Elige la moneda de referencia usada por la anal\u00edtica y las metas.",
    "settings.liveSetting": "Configuraci\u00f3n activa",
    "settings.rateLabel": "Tasa {value}",
    "settings.saveBaseCurrency": "Guardar moneda base",
    "settings.baseSaved": "Moneda base actualizada correctamente.",
    "settings.baseError": "Ocurri\u00f3 un error al actualizar la moneda base.",
    "settings.baseMissing": "La moneda seleccionada no existe.",
    "settings.baseDisabled": "La moneda seleccionada est\u00e1 desactivada.",
    "settings.baseInvalidRate": "La moneda seleccionada tiene una tasa inv\u00e1lida.",
    "settings.currencyManagement": "Gesti\u00f3n de monedas",
    "settings.currencyManagementDesc":
      "Mantiene actualizadas las tasas y decide qu\u00e9 monedas quedan activas en la app.",
    "settings.fixedDefaultCurrency": "Moneda fija por defecto",
    "settings.currentBaseCurrency": "Moneda base actual",
    "settings.customExchangeEntry": "Entrada de cambio personalizada",
    "settings.active": "Activa",
    "settings.remove": "Eliminar",
    "settings.addCurrency": "Agregar moneda",
    "settings.currencyCodeError": "El c\u00f3digo debe tener 3 letras (ej: EUR).",
    "settings.currencyRateError": "La tasa debe ser mayor a 0.",
    "settings.currencyExists": "La moneda ya existe.",
    "settings.categoryManagement": "Gesti\u00f3n de categor\u00edas",
    "settings.categoryManagementDesc":
      "Organiza categor\u00edas de ingreso y gasto con color y reglas seguras de desactivaci\u00f3n.",
    "settings.income": "Ingreso",
    "settings.expense": "Gasto",
    "settings.deactivate": "Desactivar",
    "settings.newCategoryName": "Nombre de nueva categor\u00eda",
    "settings.addCategory": "Agregar categor\u00eda",
    "settings.categoryNameRequired": "El nombre es obligatorio.",
    "settings.categoryExists": "La categor\u00eda ya existe.",
    "settings.financialGoals": "Metas financieras",
    "settings.financialGoalsDesc":
      "Define la meta de ahorro y el l\u00edmite mensual de gasto que usa el dashboard.",
    "settings.monthlySavingsTarget": "Meta mensual de ahorro",
    "settings.monthlyExpenseLimit": "L\u00edmite mensual de gasto",
    "settings.monthly": "Mensual",
    "settings.quarterly": "Trimestral",
    "settings.yearly": "Anual",
    "settings.saveGoals": "Guardar metas",
    "settings.saving": "Guardando...",
    "settings.goalsSaved": "Metas guardadas correctamente.",
    "settings.goalsError": "Error al guardar metas."
  }
};

const LanguageContext = createContext(null);

const interpolate = (template, variables = {}) =>
  template.replace(/\{(\w+)\}/g, (_, key) =>
    variables[key] !== undefined ? variables[key] : `{${key}}`
  );

const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("es");

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const t = (key, variables = {}) => {
      const template =
        translations[language]?.[key] ?? translations.en[key] ?? key;

      return interpolate(template, variables);
    };

    return { language, setLanguage, t };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

const useLanguage = () => {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage debe usarse dentro de LanguageProvider");
  }

  return context;
};

export { LanguageProvider, useLanguage };
